/*
 * src/lib/disagg/workloads.ts
 *
 * The recorded workloads the live simulator runs: Poisson arrivals, seed 1,
 * 800 requests, prompts 2,048 tokens (cv 0.5) and outputs 256 (cv 0.5),
 * generated by Disaggregated_Inference_Sim's `poisson_workload` at the
 * vendored commit (scripts/disagg_reference.py) and served from
 * /public/disagg/workloads. They are recorded rather than regenerated in the
 * browser: a JavaScript port of Python's Mersenne Twister reproduces every
 * length, but V8's Math.log differs from glibc's in the last bit for some
 * inputs, which moves arrival times by an ulp, and the engine is exact
 * enough to notice.
 */
import type { Row } from "./engine";

/** The offered loads (req/s) with a recorded workload. */
export const WORKLOAD_RATES = [2, 3, 4, 5, 6, 8, 10, 12, 14] as const;
export type WorkloadRate = (typeof WORKLOAD_RATES)[number];

export function workloadUrl(rate: WorkloadRate): string {
  return `/disagg/workloads/seed1-rate${rate}.json`;
}

const cache = new Map<WorkloadRate, Promise<Row[]>>();

/** Fetch (once) and return a recorded workload's rows. */
export function loadWorkload(rate: WorkloadRate): Promise<Row[]> {
  let p = cache.get(rate);
  if (!p) {
    p = fetch(workloadUrl(rate))
      .then((r) => {
        if (!r.ok) throw new Error(`workload ${rate} req/s: HTTP ${r.status}`);
        return r.json() as Promise<{ rows: Row[] }>;
      })
      .then((w) => w.rows);
    p.catch(() => cache.delete(rate));
    cache.set(rate, p);
  }
  return p;
}
